\hypertarget{classsocketpp_1_1sock__error}{
\section{socketpp::sock\_\-error Class Reference}
\label{classsocketpp_1_1sock__error}\index{socketpp::sock\_\-error@{socketpp::sock\_\-error}}
}
socket-related exception class  


{\tt \#include $<$SockException.h$>$}

Inheritance diagram for socketpp::sock\_\-error::\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2cm]{classsocketpp_1_1sock__error}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
\hyperlink{classsocketpp_1_1sock__error_3d017c19f53e07e813877bac42ec535b}{sock\_\-error} (const std::string \&meth, int err, const std::string \&func=\char`\"{}\char`\"{})  throw ()
\item 
\hypertarget{classsocketpp_1_1sock__error_d1c8554e6c56880c469b23cc0ffc61de}{
int \textbf{get\_\-errno} () const   throw ()}
\label{classsocketpp_1_1sock__error_d1c8554e6c56880c469b23cc0ffc61de}

\end{CompactItemize}


\subsection{Detailed Description}
socket-related exception class 

\subsection{Constructor \& Destructor Documentation}
\hypertarget{classsocketpp_1_1sock__error_3d017c19f53e07e813877bac42ec535b}{
\index{socketpp::sock\_\-error@{socketpp::sock\_\-error}!sock\_\-error@{sock\_\-error}}
\index{sock\_\-error@{sock\_\-error}!socketpp::sock_error@{socketpp::sock\_\-error}}
\subsubsection[{sock\_\-error}]{\setlength{\rightskip}{0pt plus 5cm}socketpp::sock\_\-error::sock\_\-error (const std::string \& {\em meth}, \/  int {\em err}, \/  const std::string \& {\em func} = {\tt \char`\"{}\char`\"{}})  throw ()\hspace{0.3cm}{\tt  \mbox{[}inline\mbox{]}}}}
\label{classsocketpp_1_1sock__error_3d017c19f53e07e813877bac42ec535b}


\begin{Desc}
\item[Parameters:]
\begin{description}
\item[{\em meth}]method which threw exception \item[{\em err}]errno code \item[{\em func}]C function which returned error \end{description}
\end{Desc}


The documentation for this class was generated from the following file:\begin{CompactItemize}
\item 
SockException.h\end{CompactItemize}
